# Generated by Django 6.0 on 2025-12-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_election_auto_publish_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('passcode_hash', models.CharField(blank=True, max_length=128)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Access passcode',
                'verbose_name_plural': 'Access passcodes',
            },
        ),
    ]
